image: ubuntu:18.04
before_script:
  - apt-get update
  - apt-get install -y curl
  - gitlab-runner -u root
  - curl -sL https://deb.nodesource.com/setup_10.x
  - apt-get install -y nodejs
  - npm install -g hexo-cli
  - npm install
deploy_production:
  stage: deploy
  environment: Production
  only:
    - master
  script:
    - hexo clean
    - hexo generate
    - hexo deploy