image: node:latest
before_script:
  - npm install -g hexo-cli
  - npm install
deploy_production:
  stage: deploy
  environment: Production
  only:
    - master
  script:
    - hexo clean
    - hexo generate
    - hexo deploy