language: node_js
node_js:
- 8.9.4
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_792626dc5472_key -iv $encrypted_792626dc5472_iv
  -in phoebe_rsa_nokey.enc -out ~/.ssh/phoebe_rsa_nokey -d
- chmod 600 ~/.ssh/phoebe_rsa_nokey
- npm install -g hexo-cli
install:
- npm install
before_script:
- git config --global user.name 'Avanish Shrestha'
- git config --global user.email 'avanissh@gmail.com'
script:
- hexo clean
- hexo generate
- hexo deploy
after_install:
- git remote add deploy avanish@$IP:$DEPLOY_DIR
- git push deploy master
