language: node_js
node_js:
- 8.12.0
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_22006aa8d15a_key -iv $encrypted_22006aa8d15a_iv
  -in .travis/avanish_rsa.enc -out ~/.ssh/avanish_rsa -d
- chmod 600 ~/.ssh/avanish_rsa
- ssh-add ~/.ssh/avanish_rsa
- sudo apt-get install -y expect
- npm install -g hexo-cli
install:
- npm install
before_script:
- git config --global user.name 'Avanish Shrestha'
- git config --global user.email 'avanissh@gmail.com'
script:
- hexo clean
- hexo generate
- hexo deploy
deploy:
  provider: script
  skip_cleanup: false
  script: bash .travis/deploy.sh
  on:
    branch: master
