language: node_js
node_js:
- 8.9.4
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_792626dc5472_key -iv $encrypted_792626dc5472_iv
  -in pixie_rsa.enc -out ~/.ssh/pixie_rsa -d
- openssl aes-256-cbc -K $encrypted_792626dc5472_key -iv $encrypted_792626dc5472_iv
  -in ssh_config.enc -out ~/.ssh/config -d
- chmod 600 ~/.ssh/pixie_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/pixie_rsa
- npm install -g hexo-cli
install:
- npm install
before_script:
- git config --global user.name 'Avanish Shrestha'
- git config --global user.email 'avanissh@gmail.com'
script:
- hexo clean
- hexo generate
- hexo deploy
deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
