language: node_js
node_js:
- 8.12.0
branches:
  only:
  - master
before_install:
- sudo apt-get install -y expect
- npm install -g hexo-cli
install:
- npm install -y
script:
- hexo clean
- hexo generate
- hexo deploy
after_script:
- openssl aes-256-cbc -K $encrypted_22006aa8d15a_key -iv $encrypted_22006aa8d15a_iv
  -in .travis/avanish_rsa.enc -out ~/.ssh/avanish_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 ~/.ssh/avanish_rsa
deploy:
  provider: script
  skip_cleanup: false
  script: bash .travis/deploy.sh
  on:
    branch: master
